const std = @import("std");
const internal_runtime = @import("internal/runtime/mod.zig");

/// Stable workflow namespace.
pub const workflows = @import("workflows/mod.zig");
/// Stable client composition namespace.
pub const client = @import("client/mod.zig");
/// Stable store/query reference namespace.
pub const store = @import("store/mod.zig");
/// Stable relay-pool/runtime reference namespace.
pub const runtime = @import("runtime/mod.zig");
/// Explicit HTTP seam for the current HTTP-backed workflow slices.
pub const transport = @import("transport/mod.zig");

test "root module exposes workflows store runtime plus the explicit http seam" {
    try std.testing.expect(!@hasDecl(@This(), "noztr"));
    try std.testing.expect(@TypeOf(client) == type);
    try std.testing.expect(@TypeOf(client.CliArchiveClientError) == type);
    try std.testing.expect(@TypeOf(client.CliArchiveClientConfig) == type);
    try std.testing.expect(@TypeOf(client.CliArchiveClientStorage) == type);
    try std.testing.expect(@TypeOf(client.CliArchiveClient) == type);
    try std.testing.expect(@TypeOf(client.AuthCountTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.AuthCountTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.AuthCountTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.AuthCountEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedAuthCountEvent) == type);
    try std.testing.expect(@TypeOf(client.AuthCountTurnStep) == type);
    try std.testing.expect(@TypeOf(client.AuthCountTurnResult) == type);
    try std.testing.expect(@TypeOf(client.AuthCountTurnClient) == type);
    try std.testing.expect(@TypeOf(client.AuthPublishTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.AuthPublishTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.AuthPublishTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.AuthPublishEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedAuthPublishEvent) == type);
    try std.testing.expect(@TypeOf(client.AuthPublishTurnStep) == type);
    try std.testing.expect(@TypeOf(client.AuthPublishTurnResult) == type);
    try std.testing.expect(@TypeOf(client.AuthPublishTurnClient) == type);
    try std.testing.expect(@TypeOf(client.AuthReplayTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.AuthReplayTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.AuthReplayTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.AuthReplayEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedAuthReplayEvent) == type);
    try std.testing.expect(@TypeOf(client.AuthReplayTurnStep) == type);
    try std.testing.expect(@TypeOf(client.AuthReplayTurnResult) == type);
    try std.testing.expect(@TypeOf(client.AuthReplayTurnClient) == type);
    try std.testing.expect(@TypeOf(client.AuthSubscriptionTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.AuthSubscriptionTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.AuthSubscriptionTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.AuthSubscriptionEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedAuthSubscriptionEvent) == type);
    try std.testing.expect(@TypeOf(client.AuthSubscriptionTurnStep) == type);
    try std.testing.expect(@TypeOf(client.AuthSubscriptionTurnResult) == type);
    try std.testing.expect(@TypeOf(client.AuthSubscriptionTurnClient) == type);
    try std.testing.expect(@TypeOf(client.CountJobClientError) == type);
    try std.testing.expect(@TypeOf(client.CountJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.CountJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.CountJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedCountJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.CountJobRequest) == type);
    try std.testing.expect(@TypeOf(client.CountJobReady) == type);
    try std.testing.expect(@TypeOf(client.CountJobResult) == type);
    try std.testing.expect(@TypeOf(client.CountJobClient) == type);
    try std.testing.expect(@TypeOf(client.CountTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.CountTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.CountTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.CountTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.CountTurnResult) == type);
    try std.testing.expect(@TypeOf(client.CountTurnClient) == type);
    try std.testing.expect(@TypeOf(client.LocalEntityJobClientError) == type);
    try std.testing.expect(@TypeOf(client.LocalEntityJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.LocalEntityJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.LocalEntityJobRequest) == type);
    try std.testing.expect(@TypeOf(client.LocalEntityJobResult) == type);
    try std.testing.expect(@TypeOf(client.LocalEntityJobClient) == type);
    try std.testing.expect(@TypeOf(client.LocalEventJobClientError) == type);
    try std.testing.expect(@TypeOf(client.LocalEventJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.LocalEventJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.LocalEventJobRequest) == type);
    try std.testing.expect(@TypeOf(client.LocalEventJobResult) == type);
    try std.testing.expect(@TypeOf(client.LocalEventJobClient) == type);
    try std.testing.expect(@TypeOf(client.LocalNip44JobClientError) == type);
    try std.testing.expect(@TypeOf(client.LocalNip44JobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.LocalNip44JobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.LocalNip44JobRequest) == type);
    try std.testing.expect(@TypeOf(client.LocalNip44JobResult) == type);
    try std.testing.expect(@TypeOf(client.LocalNip44JobClient) == type);
    try std.testing.expect(@TypeOf(client.LocalKeyJobClientError) == type);
    try std.testing.expect(@TypeOf(client.LocalKeyJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.LocalKeyJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.LocalKeyJobRequest) == type);
    try std.testing.expect(@TypeOf(client.LocalKeyJobResult) == type);
    try std.testing.expect(@TypeOf(client.LocalKeyJobClient) == type);
    try std.testing.expect(@TypeOf(client.MailboxJobClientError) == type);
    try std.testing.expect(@TypeOf(client.MailboxJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.MailboxJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.MailboxJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedMailboxJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.MailboxJobReady) == type);
    try std.testing.expect(@TypeOf(client.MailboxJobResult) == type);
    try std.testing.expect(@TypeOf(client.MailboxJobClient) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionTurnIntake) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionTurnResult) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionTurnClient) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionJobClientError) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedMailboxSubscriptionJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionJobRequest) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionJobIntake) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionJobReady) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionJobResult) == type);
    try std.testing.expect(@TypeOf(client.MailboxSubscriptionJobClient) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimeClientError) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimeClientConfig) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimeClientStorage) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimeResumeStorage) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimeResumeState) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimePlanStorage) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimeStep) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimePlan) == type);
    try std.testing.expect(@TypeOf(client.MailboxLongLivedDmPolicyStorage) == type);
    try std.testing.expect(@TypeOf(client.MailboxLongLivedDmPolicyStep) == type);
    try std.testing.expect(@TypeOf(client.MailboxLongLivedDmPolicyPlan) == type);
    try std.testing.expect(@TypeOf(client.MailboxDmOrchestrationStorage) == type);
    try std.testing.expect(@TypeOf(client.MailboxDmOrchestrationStep) == type);
    try std.testing.expect(@TypeOf(client.MailboxDmOrchestrationPlan) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimeAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedMailboxSyncRuntimeAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimeReplayRequest) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimeReplayIntake) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimeSubscriptionRequest) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimeSubscriptionIntake) == type);
    try std.testing.expect(@TypeOf(client.MailboxSyncRuntimeClient) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayTurnIntake) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayTurnResult) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayTurnClient) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayJobClientError) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedMailboxReplayJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayJobRequest) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayJobIntake) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayJobReady) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayJobResult) == type);
    try std.testing.expect(@TypeOf(client.MailboxReplayJobClient) == type);
    try std.testing.expect(@TypeOf(client.LocalOperatorClientError) == type);
    try std.testing.expect(@TypeOf(client.LocalOperatorClientConfig) == type);
    try std.testing.expect(@TypeOf(client.LocalKeypair) == type);
    try std.testing.expect(@TypeOf(client.LocalEventDraft) == type);
    try std.testing.expect(@TypeOf(client.LocalEventInspection) == type);
    try std.testing.expect(@TypeOf(client.LocalOperatorClient) == type);
    try std.testing.expect(@TypeOf(client.Nip03VerifyClientError) == type);
    try std.testing.expect(@TypeOf(client.Nip03VerifyClientConfig) == type);
    try std.testing.expect(@TypeOf(client.Nip03VerifyClientStorage) == type);
    try std.testing.expect(@TypeOf(client.Nip03VerifyJob) == type);
    try std.testing.expect(@TypeOf(client.Nip03VerifyCachedResult) == type);
    try std.testing.expect(@TypeOf(client.Nip03VerifyJobResult) == type);
    try std.testing.expect(@TypeOf(client.Nip03VerifyClient) == type);
    try std.testing.expect(@TypeOf(client.Nip05VerifyClientError) == type);
    try std.testing.expect(@TypeOf(client.Nip05VerifyClientConfig) == type);
    try std.testing.expect(@TypeOf(client.Nip05VerifyClientStorage) == type);
    try std.testing.expect(@TypeOf(client.Nip05LookupJob) == type);
    try std.testing.expect(@TypeOf(client.Nip05VerifyJob) == type);
    try std.testing.expect(@TypeOf(client.Nip05LookupJobResult) == type);
    try std.testing.expect(@TypeOf(client.Nip05VerifyJobResult) == type);
    try std.testing.expect(@TypeOf(client.Nip05VerifyClient) == type);
    try std.testing.expect(@TypeOf(client.Nip39VerifyClientError) == type);
    try std.testing.expect(@TypeOf(client.Nip39VerifyClientConfig) == type);
    try std.testing.expect(@TypeOf(client.Nip39VerifyClientStorage) == type);
    try std.testing.expect(@TypeOf(client.Nip39VerifyJob) == type);
    try std.testing.expect(@TypeOf(client.Nip39VerifySummary) == type);
    try std.testing.expect(@TypeOf(client.Nip39VerifyJobResult) == type);
    try std.testing.expect(@TypeOf(client.Nip39VerifyClient) == type);
    try std.testing.expect(@TypeOf(client.PublishJobClientError) == type);
    try std.testing.expect(@TypeOf(client.PublishJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.PublishJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.PublishJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedPublishJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.PublishJobRequest) == type);
    try std.testing.expect(@TypeOf(client.PublishJobReady) == type);
    try std.testing.expect(@TypeOf(client.PublishJobResult) == type);
    try std.testing.expect(@TypeOf(client.PublishJobClient) == type);
    try std.testing.expect(@TypeOf(client.PublishClientError) == type);
    try std.testing.expect(@TypeOf(client.PublishClientConfig) == type);
    try std.testing.expect(@TypeOf(client.PublishClientStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedPublishEvent) == type);
    try std.testing.expect(@TypeOf(client.PublishTarget) == type);
    try std.testing.expect(@TypeOf(client.TargetedPublishEvent) == type);
    try std.testing.expect(@TypeOf(client.PublishClient) == type);
    try std.testing.expect(@TypeOf(client.PublishTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.PublishTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.PublishTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.PublishTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.PublishTurnResult) == type);
    try std.testing.expect(@TypeOf(client.PublishTurnClient) == type);
    try std.testing.expect(@TypeOf(client.RelayAuthClientError) == type);
    try std.testing.expect(@TypeOf(client.RelayAuthClientConfig) == type);
    try std.testing.expect(@TypeOf(client.RelayAuthClientStorage) == type);
    try std.testing.expect(@TypeOf(client.RelayAuthTarget) == type);
    try std.testing.expect(@TypeOf(client.RelayAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedRelayAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.RelayAuthClient) == type);
    try std.testing.expect(@TypeOf(client.RelayDirectoryJobClientError) == type);
    try std.testing.expect(@TypeOf(client.RelayDirectoryJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.RelayDirectoryJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.RelayDirectoryRefreshJob) == type);
    try std.testing.expect(@TypeOf(client.RelayDirectoryRefreshJobResult) == type);
    try std.testing.expect(@TypeOf(client.RelayDirectoryJobClient) == type);
    try std.testing.expect(@TypeOf(client.RelayExchangeClientError) == type);
    try std.testing.expect(@TypeOf(client.RelayExchangeClientConfig) == type);
    try std.testing.expect(@TypeOf(client.RelayExchangeClientStorage) == type);
    try std.testing.expect(@TypeOf(client.PublishExchangeRequest) == type);
    try std.testing.expect(@TypeOf(client.PublishExchangeOutcome) == type);
    try std.testing.expect(@TypeOf(client.CountExchangeRequest) == type);
    try std.testing.expect(@TypeOf(client.CountExchangeOutcome) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionExchangeRequest) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionExchangeOutcome) == type);
    try std.testing.expect(@TypeOf(client.CloseExchangeRequest) == type);
    try std.testing.expect(@TypeOf(client.RelayExchangeClient) == type);
    try std.testing.expect(@TypeOf(client.RelayQueryClientError) == type);
    try std.testing.expect(@TypeOf(client.RelayQueryClientConfig) == type);
    try std.testing.expect(@TypeOf(client.RelayQueryClientStorage) == type);
    try std.testing.expect(@TypeOf(client.RelayQueryTarget) == type);
    try std.testing.expect(@TypeOf(client.TargetedSubscriptionRequest) == type);
    try std.testing.expect(@TypeOf(client.TargetedCountRequest) == type);
    try std.testing.expect(@TypeOf(client.TargetedCloseRequest) == type);
    try std.testing.expect(@TypeOf(client.RelayQueryClient) == type);
    try std.testing.expect(@TypeOf(client.RelayWorkspaceClientError) == type);
    try std.testing.expect(@TypeOf(client.RelayWorkspaceClientConfig) == type);
    try std.testing.expect(@TypeOf(client.RelayWorkspaceClientStorage) == type);
    try std.testing.expect(@TypeOf(client.RelayWorkspaceRestoreResult) == type);
    try std.testing.expect(@TypeOf(client.RelayWorkspaceClient) == type);
    try std.testing.expect(@TypeOf(client.ReplayJobClientError) == type);
    try std.testing.expect(@TypeOf(client.ReplayJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.ReplayJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.ReplayJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedReplayJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.ReplayJobRequest) == type);
    try std.testing.expect(@TypeOf(client.ReplayJobIntake) == type);
    try std.testing.expect(@TypeOf(client.ReplayJobReady) == type);
    try std.testing.expect(@TypeOf(client.ReplayJobResult) == type);
    try std.testing.expect(@TypeOf(client.ReplayJobClient) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayClientError) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayClientConfig) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayClientStorage) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayTarget) == type);
    try std.testing.expect(@TypeOf(client.TargetedReplayRequest) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayClient) == type);
    try std.testing.expect(@TypeOf(client.ReplayCheckpointAdvanceClientError) == type);
    try std.testing.expect(@TypeOf(client.ReplayCheckpointAdvanceClientConfig) == type);
    try std.testing.expect(@TypeOf(client.ReplayCheckpointAdvanceState) == type);
    try std.testing.expect(@TypeOf(client.ReplayCheckpointAdvanceCandidate) == type);
    try std.testing.expect(@TypeOf(client.ReplayCheckpointSaveTarget) == type);
    try std.testing.expect(@TypeOf(client.ReplayCheckpointAdvanceClient) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayExchangeClientError) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayExchangeClientConfig) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayExchangeClientStorage) == type);
    try std.testing.expect(@TypeOf(client.ReplayExchangeRequest) == type);
    try std.testing.expect(@TypeOf(client.ReplayExchangeOutcome) == type);
    try std.testing.expect(@TypeOf(client.ReplayCloseRequest) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayExchangeClient) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.ReplayTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.ReplayTurnIntake) == type);
    try std.testing.expect(@TypeOf(client.ReplayTurnResult) == type);
    try std.testing.expect(@TypeOf(client.RelayReplayTurnClient) == type);
    try std.testing.expect(@TypeOf(client.RelayResponseClientError) == type);
    try std.testing.expect(@TypeOf(client.RelayResponseClientConfig) == type);
    try std.testing.expect(@TypeOf(client.RelaySubscriptionTranscriptStorage) == type);
    try std.testing.expect(@TypeOf(client.RelaySubscriptionEventMessage) == type);
    try std.testing.expect(@TypeOf(client.RelaySubscriptionEoseMessage) == type);
    try std.testing.expect(@TypeOf(client.RelaySubscriptionClosedMessage) == type);
    try std.testing.expect(@TypeOf(client.RelaySubscriptionMessageOutcome) == type);
    try std.testing.expect(@TypeOf(client.RelayCountMessage) == type);
    try std.testing.expect(@TypeOf(client.RelayPublishOkMessage) == type);
    try std.testing.expect(@TypeOf(client.RelayNoticeMessage) == type);
    try std.testing.expect(@TypeOf(client.RelayAuthChallengeMessage) == type);
    try std.testing.expect(@TypeOf(client.RelayResponseClient) == type);
    try std.testing.expect(@TypeOf(client.SignerConnectJobClientError) == type);
    try std.testing.expect(@TypeOf(client.SignerConnectJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.SignerConnectJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.SignerConnectJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedSignerConnectJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.SignerConnectJobRequest) == type);
    try std.testing.expect(@TypeOf(client.SignerConnectJobReady) == type);
    try std.testing.expect(@TypeOf(client.SignerConnectJobResult) == type);
    try std.testing.expect(@TypeOf(client.SignerConnectJobClient) == type);
    try std.testing.expect(@TypeOf(client.SignerClientError) == type);
    try std.testing.expect(@TypeOf(client.SignerClientConfig) == type);
    try std.testing.expect(@TypeOf(client.SignerClientRequestStorage) == type);
    try std.testing.expect(@TypeOf(client.SignerClientStorage) == type);
    try std.testing.expect(@TypeOf(client.SignerClient) == type);
    try std.testing.expect(@TypeOf(client.SignerNip44EncryptJobClientError) == type);
    try std.testing.expect(@TypeOf(client.SignerNip44EncryptJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.SignerNip44EncryptJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.SignerNip44EncryptJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedSignerNip44EncryptJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.SignerNip44EncryptJobRequest) == type);
    try std.testing.expect(@TypeOf(client.SignerNip44EncryptJobReady) == type);
    try std.testing.expect(@TypeOf(client.SignerNip44EncryptJobResult) == type);
    try std.testing.expect(@TypeOf(client.SignerNip44EncryptJobClient) == type);
    try std.testing.expect(@TypeOf(client.SignerPubkeyJobClientError) == type);
    try std.testing.expect(@TypeOf(client.SignerPubkeyJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.SignerPubkeyJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.SignerPubkeyJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedSignerPubkeyJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.SignerPubkeyJobRequest) == type);
    try std.testing.expect(@TypeOf(client.SignerPubkeyJobReady) == type);
    try std.testing.expect(@TypeOf(client.SignerPubkeyJobResult) == type);
    try std.testing.expect(@TypeOf(client.SignerPubkeyJobClient) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionJobClientError) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedSubscriptionJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionJobRequest) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionJobIntake) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionJobReady) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionJobResult) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionJobClient) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionTurnState) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionTurnIntake) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionTurnCompletion) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionTurnResult) == type);
    try std.testing.expect(@TypeOf(client.SubscriptionTurnClient) == type);
    try std.testing.expect(@TypeOf(store) == type);
    try std.testing.expect(@TypeOf(store.RelayInfoRecord) == type);
    try std.testing.expect(@TypeOf(store.RelayInfoResultPage) == type);
    try std.testing.expect(@TypeOf(store.RelayInfoStore) == type);
    try std.testing.expect(@TypeOf(store.MemoryRelayInfoStore) == type);
    try std.testing.expect(@TypeOf(store.ClientStore) == type);
    try std.testing.expect(@TypeOf(store.ClientEventRecord) == type);
    try std.testing.expect(@TypeOf(store.ClientCheckpointRecord) == type);
    try std.testing.expect(@TypeOf(store.ClientQuery) == type);
    try std.testing.expect(@TypeOf(store.QueryResultPage(store.ClientEventRecord)) == type);
    try std.testing.expect(@TypeOf(store.EventCursor) == type);
    try std.testing.expect(@TypeOf(store.IndexSelection) == type);
    try std.testing.expect(@TypeOf(store.MemoryClientStore) == type);
    try std.testing.expect(@TypeOf(store.EventArchive) == type);
    try std.testing.expect(@TypeOf(store.RelayRegistryArchive) == type);
    try std.testing.expect(@TypeOf(store.RelayCheckpointArchive) == type);
    try std.testing.expect(@TypeOf(store.RelayLocalGroupArchive) == type);
    try std.testing.expect(@TypeOf(runtime) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPlanStorage) == type);
    try std.testing.expectEqual(@as(u8, 8), runtime.subscription_specs_capacity);
    try std.testing.expectEqual(@as(u8, 8), runtime.replay_specs_capacity);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCheckpointAction) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPublishAction) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPublishEntry) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPublishStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPublishPlan) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPublishStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolAuthAction) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolAuthEntry) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolAuthStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolAuthPlan) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolAuthStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCheckpointError) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolMemberError) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolMemberRecord) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolMemberStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolMemberSet) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCheckpointRecord) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCheckpointStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCheckpointSet) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCheckpointStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelaySubscriptionError) == type);
    try std.testing.expect(@TypeOf(runtime.RelaySubscriptionSpec) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolSubscriptionAction) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolSubscriptionEntry) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolSubscriptionStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolSubscriptionPlan) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolSubscriptionStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelayCountError) == type);
    try std.testing.expect(@TypeOf(runtime.RelayCountSpec) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCountAction) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCountEntry) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCountStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCountPlan) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCountStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelayReplayError) == type);
    try std.testing.expect(@TypeOf(runtime.RelayReplaySpec) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolReplayAction) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolReplayEntry) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolReplayStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolReplayPlan) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolReplayStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPool) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPlan) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolStep) == type);
    try std.testing.expect(@TypeOf(transport) == type);
    try std.testing.expect(@TypeOf(internal_runtime.RelayIoConnection) == type);
    try std.testing.expect(@TypeOf(internal_runtime.Clock) == type);
    try std.testing.expect(@TypeOf(internal_runtime.TaskDriver) == type);
    try std.testing.expect(@TypeOf(transport.HttpClient) == type);
    try std.testing.expect(@TypeOf(transport.HttpError) == type);
    try std.testing.expect(@TypeOf(transport.HttpRequest) == type);
    try std.testing.expect(!@hasDecl(@This(), "relay"));
    try std.testing.expect(@TypeOf(workflows) == type);
    try std.testing.expect(!@hasDecl(@This(), "policy"));
    try std.testing.expect(!@hasDecl(@This(), "sync"));
    try std.testing.expect(!@hasDecl(@This(), "Config"));
    try std.testing.expect(!@hasDecl(@This(), "testing"));
}

test "root smoke uses noztr stable helper" {
    const noztr = @import("noztr");
    const parsed_method = try noztr.nip46_remote_signing.method_parse("connect");
    try std.testing.expectEqual(.connect, parsed_method);
}

test "root smoke pins hardened noztr nip46 direct-helper typed errors" {
    const noztr = @import("noztr");

    var overlong_token: [noztr.limits.tag_item_bytes_max + 1]u8 = undefined;
    @memset(overlong_token[0..], 'a');
    try std.testing.expectError(
        error.InvalidMethod,
        noztr.nip46_remote_signing.method_parse(overlong_token[0..]),
    );

    overlong_token[0] = 'p';
    overlong_token[1] = ':';
    try std.testing.expectError(
        error.InvalidPermission,
        noztr.nip46_remote_signing.permission_parse(overlong_token[0..]),
    );
}

test "phase3 relay directory fetches nip11 over explicit seams" {
    const sdk_store = @import("store/mod.zig");
    const relay_directory = @import("relay/directory.zig");
    const testing = @import("testing/mod.zig");
    const json =
        \\{"name":"alpha","pubkey":"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef","supported_nips":[11,42]}
    ;
    var fake_http = testing.FakeHttp.init("https://relay.test", json);
    var memory_store = sdk_store.MemoryStore{};
    var directory = relay_directory.RelayDirectory.init(memory_store.asRelayInfoStore());
    var url_buffer: [128]u8 = undefined;
    var response_buffer: [256]u8 = undefined;
    var parse_scratch: [4096]u8 = undefined;

    const record = try directory.refresh(
        fake_http.client(),
        "wss://relay.test",
        &url_buffer,
        &response_buffer,
        &parse_scratch,
    );
    try std.testing.expectEqualStrings("wss://relay.test", record.relayUrl());
    try std.testing.expectEqualStrings("alpha", record.nameSlice());
}

test "phase3 session helpers stay internal and explicit" {
    const testing = @import("testing/mod.zig");
    const relay_pool = @import("relay/pool.zig");
    var pool = relay_pool.Pool.init();
    const relay_index = try pool.addRelay("wss://relay.one");
    const relay_session = pool.getRelay(relay_index) orelse unreachable;
    const fake_relay = testing.FakeRelay{
        .relay_url = "wss://relay.one",
        .challenge = "challenge-1",
    };
    try fake_relay.requireAuth(relay_session);
    try std.testing.expect(!relay_session.canSendRequests());
}

test "phase4 exposes the remote signer workflow surface" {
    try std.testing.expect(@TypeOf(workflows.RemoteSignerSession) == type);
    try std.testing.expect(@TypeOf(workflows.RemoteSignerPubkeyTextRequest) == type);
    try std.testing.expect(@TypeOf(workflows.RemoteSignerRequestContext) == type);
    try std.testing.expect(@TypeOf(workflows.RemoteSignerTextResponse) == type);
    try std.testing.expect(@TypeOf(workflows.RemoteSignerRelayPoolStorage) == type);
    try std.testing.expect(@TypeOf(workflows.RemoteSignerRelayPoolRuntimeStorage) == type);
}

test "phase4b exposes the legacy dm workflow surface" {
    try std.testing.expect(@TypeOf(workflows.LegacyDmSession) == type);
    try std.testing.expect(@TypeOf(workflows.LegacyDmError) == type);
    try std.testing.expect(@TypeOf(workflows.LegacyDmDirectMessageRequest) == type);
    try std.testing.expect(@TypeOf(workflows.LegacyDmOutboundStorage) == type);
    try std.testing.expect(@TypeOf(workflows.PreparedLegacyDmEvent) == type);
    try std.testing.expect(@TypeOf(workflows.LegacyDmMessageOutcome) == type);
}

test "phase4c exposes the legacy dm publish job floor" {
    try std.testing.expect(@TypeOf(client.LegacyDmPublishJobClientError) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmPublishJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmPublishJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmPublishJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedLegacyDmPublishJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmPublishJobRequest) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmPublishJobReady) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmPublishJobResult) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmPublishJobClient) == type);
}

test "phase4d exposes the legacy dm transcript turn floors" {
    try std.testing.expect(@TypeOf(client.LegacyDmReplayTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayTurnIntake) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayTurnResult) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayTurnClient) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionTurnIntake) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionTurnResult) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionTurnClient) == type);
}

test "phase4e exposes the legacy dm replay live runtime floors" {
    try std.testing.expect(@TypeOf(client.LegacyDmReplayJobClientError) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedLegacyDmReplayJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayJobRequest) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayJobIntake) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayJobReady) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayJobResult) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmReplayJobClient) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionJobClientError) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedLegacyDmSubscriptionJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionJobRequest) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionJobIntake) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionJobReady) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionJobResult) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSubscriptionJobClient) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimeClientError) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimeClientConfig) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimeClientStorage) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimeResumeStorage) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimeResumeState) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimePlanStorage) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimePlan) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimeStep) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmLongLivedDmPolicyStorage) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmLongLivedDmPolicyStep) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmLongLivedDmPolicyPlan) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmOrchestrationStorage) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmOrchestrationStep) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmOrchestrationPlan) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimeAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.PreparedLegacyDmSyncRuntimeAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimeReplayRequest) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimeReplayIntake) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimeSubscriptionRequest) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimeSubscriptionIntake) == type);
    try std.testing.expect(@TypeOf(client.LegacyDmSyncRuntimeClient) == type);
}

test "phase5 exposes the mailbox workflow surface" {
    try std.testing.expect(@TypeOf(workflows.MailboxSession) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxOutboundBuffer) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxFileMessageOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxEnvelopeOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxFileDimensions) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxDeliveryStorage) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxDeliveryRole) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxDeliveryPlan) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxDeliveryStep) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxRuntimeAction) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxRuntimeEntry) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxRuntimeStep) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxRelayPoolStorage) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxRelayPoolRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxWorkflowAction) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxWorkflowEntry) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxWorkflowStep) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxWorkflowStorage) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxWorkflowRequest) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxWorkflowPlan) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxRuntimePlan) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxReceiveTurnStorage) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxReceiveTurnRequest) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxReceiveTurnResult) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxSyncTurnStorage) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxSyncTurnRequest) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxSyncTurnResult) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxDirectMessageRequest) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxFileMessageRequest) == type);
    try std.testing.expect(@TypeOf(workflows.MailboxOutboundMessage) == type);
}

test "phase6 exposes the identity verifier workflow surface" {
    try std.testing.expect(@TypeOf(workflows.IdentityVerifier) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityVerificationCacheResult) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityVerificationCacheRecord) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityVerificationCacheError) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityVerificationCache) == type);
    try std.testing.expect(@TypeOf(workflows.MemoryIdentityVerificationCache) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityProfileStorePutOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityProfileStoreError) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredClaim) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityProfileRecord) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityProfileMatch) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityProfileDiscoveryRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileDiscoveryEntry) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileDiscoveryStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileDiscoveryRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityLatestStoredProfileRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileFreshness) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileFallbackPolicy) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityLatestStoredProfileFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityLatestStoredProfileFreshness) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityPreferredStoredProfileRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityPreferredStoredProfile) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileDiscoveryFreshnessEntry) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileDiscoveryFreshnessStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileDiscoveryFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTarget) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetDiscoveryGroup) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetDiscoveryStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetDiscoveryRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetDiscoveryFreshnessGroup) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetDiscoveryFreshnessStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetDiscoveryFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityLatestStoredProfileTargetEntry) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityLatestStoredProfileTargetStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityLatestStoredProfileTargetRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityPreferredStoredProfileTargetEntry) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityPreferredStoredProfileTargetStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityPreferredStoredProfileTargetSelectionRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetLatestFreshnessEntry) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetLatestFreshnessStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetLatestFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityPreferredStoredProfileTargetRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityPreferredStoredProfileTarget) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshEntry) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshPlan) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshStep) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRuntimeAction) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRuntimeRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRuntimePlan) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRuntimeStep) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetPolicyEntry) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetPolicyGroup) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetPolicyStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetPolicyRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetPolicyPlan) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshCadenceAction) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshCadenceEntry) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshCadenceGroup) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshCadenceStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshCadenceRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshCadencePlan) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshCadenceStep) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshBatchStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshBatchRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshBatchPlan) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetRefreshBatchStep) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetTurnPolicyAction) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetTurnPolicyEntry) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetTurnPolicyGroup) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetTurnPolicyStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetTurnPolicyRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetTurnPolicyPlan) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetTurnPolicyStep) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetLatestFreshnessPlan) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileTargetLatestFreshnessStep) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileRuntimeAction) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileRuntimeRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileRuntimePlan) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileRuntimeStep) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileRefreshEntry) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileRefreshStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileRefreshRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileRefreshPlan) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileRefreshStep) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityProfileStore) == type);
    try std.testing.expect(@TypeOf(workflows.MemoryIdentityProfileStore) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityVerificationStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityVerificationRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityProviderDetails) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityClaimVerificationOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityClaimVerification) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityProfileVerificationStorage) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityProfileVerificationRequest) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityProfileVerificationSummary) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityRememberedProfileVerification) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityRememberedProfileVerificationError) == type);
    try std.testing.expect(@TypeOf(workflows.IdentityStoredProfileDiscoveryError) == type);
}

test "phase7 exposes the opentimestamps verifier workflow surface" {
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsVerifier) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsProofStoreError) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsProofRecord) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsProofStore) == type);
    try std.testing.expect(@TypeOf(workflows.MemoryOpenTimestampsProofStore) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsVerificationStorePutOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsVerificationStoreError) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationRecord) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationMatch) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsVerificationDiscoveryRequest) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationDiscoveryEntry) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationDiscoveryStorage) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationDiscoveryRequest) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsLatestStoredVerificationRequest) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationFreshness) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsLatestStoredVerificationFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsLatestStoredVerificationFreshness) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationDiscoveryFreshnessEntry) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationDiscoveryFreshnessStorage) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationDiscoveryFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationTarget) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsLatestStoredVerificationTargetEntry) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsLatestStoredVerificationTargetStorage) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsLatestStoredVerificationTargetRequest) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationFallbackPolicy) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsPreferredStoredVerificationRequest) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsPreferredStoredVerification) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsPreferredStoredVerificationTargetEntry) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsPreferredStoredVerificationTargetStorage) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsPreferredStoredVerificationTargetRequest) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationRuntimeAction) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationRuntimeRequest) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationRuntimePlan) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationRuntimeStep) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationRefreshEntry) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationRefreshStorage) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationRefreshRequest) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationRefreshPlan) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationRefreshStep) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationTargetRefreshEntry) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationTargetRefreshStorage) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationTargetRefreshRequest) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationTargetRefreshPlan) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationTargetRefreshStep) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsVerificationStore) == type);
    try std.testing.expect(@TypeOf(workflows.MemoryOpenTimestampsVerificationStore) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsRemoteProofRequest) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsRemoteVerification) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsRememberedRemoteVerification) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsRememberedRemoteVerificationError) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsStoredVerificationDiscoveryError) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsFetchFailure) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsRemoteVerificationOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.OpenTimestampsRememberedRemoteVerificationOutcome) == type);
}

test "phase8 exposes the nip05 resolver workflow surface" {
    try std.testing.expect(@TypeOf(workflows.Nip05Resolver) == type);
    try std.testing.expect(@TypeOf(workflows.Nip05LookupStorage) == type);
    try std.testing.expect(@TypeOf(workflows.Nip05LookupRequest) == type);
    try std.testing.expect(@TypeOf(workflows.Nip05VerificationRequest) == type);
}

test "phase9 exposes the group session workflow surface" {
    try std.testing.expect(@TypeOf(workflows.GroupClient) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleet) == type);
    try std.testing.expect(@TypeOf(workflows.GroupRelayState) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetRelayStatus) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetRuntimeAction) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetBackgroundAction) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetBackgroundEntry) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetBackgroundRuntimeStep) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetBackgroundRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetBackgroundRuntimeRequest) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetBackgroundRuntimePlan) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetRuntimeEntry) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetRuntimeStep) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetRuntimePlan) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetEventOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetBatchOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetRelayDivergence) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetConsistencyReport) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetConsistencyStep) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetReconcileOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetTargetReconcileOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetPublishStep) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetMergeSelection) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetMergedCheckpoint) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetMergeApplyOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetCheckpointStorage) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetMergeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetCheckpointContext) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetMergeContext) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetCheckpointSet) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetCheckpointStorePutOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetCheckpointStoreError) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetCheckpointRecord) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetCheckpointStore) == type);
    try std.testing.expect(@TypeOf(workflows.MemoryGroupFleetCheckpointStore) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetStorePersistOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetStoreRestoreOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetPublishStorage) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetPublishContext) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetPutUserDraft) == type);
    try std.testing.expect(@TypeOf(workflows.GroupFleetRemoveUserDraft) == type);
    try std.testing.expect(@TypeOf(workflows.GroupCheckpointBuffers) == type);
    try std.testing.expect(@TypeOf(workflows.GroupCheckpointContext) == type);
    try std.testing.expect(@TypeOf(workflows.GroupCheckpoint) == type);
    try std.testing.expect(@TypeOf(workflows.GroupClientStorage) == type);
    try std.testing.expect(@TypeOf(workflows.GroupClientConfig) == type);
    try std.testing.expect(@TypeOf(workflows.GroupClientView) == type);
    try std.testing.expect(@TypeOf(workflows.GroupClientEventOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.GroupClientBatchSummary) == type);
    try std.testing.expect(@TypeOf(workflows.GroupSession) == type);
    try std.testing.expect(@TypeOf(workflows.GroupSessionStorage) == type);
    try std.testing.expect(@TypeOf(workflows.GroupSessionConfig) == type);
    try std.testing.expect(@TypeOf(workflows.GroupSessionView) == type);
    try std.testing.expect(@TypeOf(workflows.GroupOutboundBuffer) == type);
    try std.testing.expect(@TypeOf(workflows.GroupPublishContext) == type);
    try std.testing.expect(@TypeOf(workflows.GroupOutboundEvent) == type);
    try std.testing.expect(@TypeOf(workflows.GroupMetadataDraft) == type);
    try std.testing.expect(@TypeOf(workflows.GroupAdminsDraft) == type);
    try std.testing.expect(@TypeOf(workflows.GroupMembersDraft) == type);
    try std.testing.expect(@TypeOf(workflows.GroupRolesDraft) == type);
    try std.testing.expect(@TypeOf(workflows.GroupJoinRequestDraft) == type);
    try std.testing.expect(@TypeOf(workflows.GroupLeaveRequestDraft) == type);
    try std.testing.expect(@TypeOf(workflows.GroupPutUserDraft) == type);
    try std.testing.expect(@TypeOf(workflows.GroupRemoveUserDraft) == type);
    try std.testing.expect(@TypeOf(workflows.GroupObservedEventKind) == type);
    try std.testing.expect(@TypeOf(workflows.GroupJoinRequestInfo) == type);
    try std.testing.expect(@TypeOf(workflows.GroupLeaveRequestInfo) == type);
}
