const std = @import("std");
const internal_runtime = @import("internal/runtime/mod.zig");

/// Stable workflow namespace.
pub const workflows = @import("workflows/mod.zig");
/// Stable client composition namespace.
pub const client = @import("client/mod.zig");
/// Stable store/query reference namespace.
pub const store = @import("store/mod.zig");
/// Stable relay-pool/runtime reference namespace.
pub const runtime = @import("runtime/mod.zig");
/// Explicit HTTP seam for the current HTTP-backed workflow slices.
pub const transport = @import("transport/mod.zig");

test "root module exposes grouped client and workflow namespaces" {
    try std.testing.expect(!@hasDecl(@This(), "noztr"));
    try std.testing.expect(@TypeOf(client) == type);
    try std.testing.expect(@TypeOf(client.local) == type);
    try std.testing.expect(@TypeOf(client.local.operator.LocalOperatorClient) == type);
    try std.testing.expect(@TypeOf(client.relay) == type);
    try std.testing.expect(@TypeOf(client.relay.session.RelaySessionClient) == type);
    try std.testing.expect(@TypeOf(client.signer) == type);
    try std.testing.expect(@TypeOf(client.signer.browser.Nip07BrowserProvider) == type);
    try std.testing.expect(@TypeOf(client.signer.capability.SignerCapabilityProfile) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClient) == type);
    try std.testing.expect(@TypeOf(client.dm) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeClient) == type);
    try std.testing.expect(@TypeOf(client.identity) == type);
    try std.testing.expect(@TypeOf(client.identity.nip39.Nip39VerifyClient) == type);
    try std.testing.expect(@TypeOf(client.proof) == type);
    try std.testing.expect(@TypeOf(client.proof.nip03.Nip03VerifyClient) == type);
    try std.testing.expect(@TypeOf(client.groups) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClient) == type);
    try std.testing.expect(@TypeOf(workflows.groups) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleet) == type);
    try std.testing.expect(@TypeOf(workflows.identity) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityVerifier) == type);
    try std.testing.expect(@TypeOf(workflows.dm) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxSession) == type);
    try std.testing.expect(@TypeOf(workflows.proof) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsVerifier) == type);
    try std.testing.expect(@TypeOf(workflows.signer) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerSession) == type);
    try std.testing.expect(@TypeOf(client.local.archive.CliArchiveClientError) == type);
    try std.testing.expect(@TypeOf(client.local.archive.CliArchiveClientConfig) == type);
    try std.testing.expect(@TypeOf(client.local.archive.CliArchiveClientStorage) == type);
    try std.testing.expect(@TypeOf(client.local.archive.CliArchiveClient) == type);
    try std.testing.expect(@TypeOf(client.local.state.LocalStateClientError) == type);
    try std.testing.expect(@TypeOf(client.local.state.LocalStateClientConfig) == type);
    try std.testing.expect(@TypeOf(client.local.state.LocalStateClientStorage) == type);
    try std.testing.expect(@TypeOf(client.local.state.LocalStateRestoreResult) == type);
    try std.testing.expect(@TypeOf(client.local.state.LocalStateClient) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_count_turn.AuthCountTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_count_turn.AuthCountTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_count_turn.AuthCountTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_count_turn.AuthCountEventStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_count_turn.PreparedAuthCountEvent) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_count_turn.AuthCountTurnStep) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_count_turn.AuthCountTurnResult) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_count_turn.AuthCountTurnClient) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_publish_turn.AuthPublishTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_publish_turn.AuthPublishTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_publish_turn.AuthPublishTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_publish_turn.AuthPublishEventStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_publish_turn.PreparedAuthPublishEvent) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_publish_turn.AuthPublishTurnStep) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_publish_turn.AuthPublishTurnResult) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_publish_turn.AuthPublishTurnClient) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_replay_turn.AuthReplayTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_replay_turn.AuthReplayTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_replay_turn.AuthReplayTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_replay_turn.AuthReplayEventStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_replay_turn.PreparedAuthReplayEvent) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_replay_turn.AuthReplayTurnStep) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_replay_turn.AuthReplayTurnResult) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_replay_turn.AuthReplayTurnClient) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_subscription_turn.AuthSubscriptionTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_subscription_turn.AuthSubscriptionTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_subscription_turn.AuthSubscriptionTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_subscription_turn.AuthSubscriptionEventStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_subscription_turn.PreparedAuthSubscriptionEvent) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_subscription_turn.AuthSubscriptionTurnStep) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_subscription_turn.AuthSubscriptionTurnResult) == type);
    try std.testing.expect(@TypeOf(client.relay.auth_subscription_turn.AuthSubscriptionTurnClient) == type);
    try std.testing.expect(@TypeOf(client.relay.count_job.CountJobClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.count_job.CountJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.count_job.CountJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.count_job.CountJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.count_job.PreparedCountJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.relay.count_job.CountJobRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.count_job.CountJobReady) == type);
    try std.testing.expect(@TypeOf(client.relay.count_job.CountJobResult) == type);
    try std.testing.expect(@TypeOf(client.relay.count_job.CountJobClient) == type);
    try std.testing.expect(@TypeOf(client.relay.count_turn.CountTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.count_turn.CountTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.count_turn.CountTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.count_turn.CountTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.count_turn.CountTurnResult) == type);
    try std.testing.expect(@TypeOf(client.relay.count_turn.CountTurnClient) == type);
    try std.testing.expect(@TypeOf(client.local.entities.LocalEntityJobClientError) == type);
    try std.testing.expect(@TypeOf(client.local.entities.LocalEntityJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.local.entities.LocalEntityJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.local.entities.LocalEntityJobRequest) == type);
    try std.testing.expect(@TypeOf(client.local.entities.LocalEntityJobResult) == type);
    try std.testing.expect(@TypeOf(client.local.entities.LocalEntityJobClient) == type);
    try std.testing.expect(@TypeOf(client.local.events.LocalEventJobClientError) == type);
    try std.testing.expect(@TypeOf(client.local.events.LocalEventJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.local.events.LocalEventJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.local.events.LocalEventJobRequest) == type);
    try std.testing.expect(@TypeOf(client.local.events.LocalEventJobResult) == type);
    try std.testing.expect(@TypeOf(client.local.events.LocalEventJobClient) == type);
    try std.testing.expect(@TypeOf(client.local.nip44.LocalNip44JobClientError) == type);
    try std.testing.expect(@TypeOf(client.local.nip44.LocalNip44JobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.local.nip44.LocalNip44JobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.local.nip44.LocalNip44JobRequest) == type);
    try std.testing.expect(@TypeOf(client.local.nip44.LocalNip44JobResult) == type);
    try std.testing.expect(@TypeOf(client.local.nip44.LocalNip44JobClient) == type);
    try std.testing.expect(@TypeOf(client.local.keys.LocalKeyJobClientError) == type);
    try std.testing.expect(@TypeOf(client.local.keys.LocalKeyJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.local.keys.LocalKeyJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.local.keys.LocalKeyJobRequest) == type);
    try std.testing.expect(@TypeOf(client.local.keys.LocalKeyJobResult) == type);
    try std.testing.expect(@TypeOf(client.local.keys.LocalKeyJobClient) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.job.MailboxJobClientError) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.job.MailboxJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.job.MailboxJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.job.MailboxJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.job.PreparedMailboxJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.job.MailboxJobReady) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.job.MailboxJobResult) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.job.MailboxJobClient) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_turn.MailboxSubscriptionTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_turn.MailboxSubscriptionTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_turn.MailboxSubscriptionTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_turn.MailboxSubscriptionTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_turn.MailboxSubscriptionTurnIntake) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_turn.MailboxSubscriptionTurnResult) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_turn.MailboxSubscriptionTurnClient) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_job.MailboxSubscriptionJobClientError) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_job.MailboxSubscriptionJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_job.MailboxSubscriptionJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_job.MailboxSubscriptionJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_job.PreparedMailboxSubscriptionJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_job.MailboxSubscriptionJobRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_job.MailboxSubscriptionJobIntake) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_job.MailboxSubscriptionJobReady) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_job.MailboxSubscriptionJobResult) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.subscription_job.MailboxSubscriptionJobClient) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeClientError) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeClientConfig) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeClientStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeResumeStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeResumeState) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimePlanStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeStep) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimePlan) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxLongLivedDmPolicyStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxLongLivedDmPolicyStep) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxLongLivedDmPolicyPlan) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxDmOrchestrationStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxDmOrchestrationStep) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxDmOrchestrationPlan) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxDmRuntimeCadenceRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxDmRuntimeCadenceStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxDmRuntimeCadenceWaitReason) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxDmRuntimeCadenceWait) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxDmRuntimeCadenceStep) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxDmRuntimeCadencePlan) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.PreparedMailboxSyncRuntimeAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeReplayRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeReplayIntake) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeSubscriptionRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeSubscriptionIntake) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.sync_runtime.MailboxSyncRuntimeClient) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_turn.MailboxReplayTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_turn.MailboxReplayTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_turn.MailboxReplayTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_turn.MailboxReplayTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_turn.MailboxReplayTurnIntake) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_turn.MailboxReplayTurnResult) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_turn.MailboxReplayTurnClient) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_job.MailboxReplayJobClientError) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_job.MailboxReplayJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_job.MailboxReplayJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_job.MailboxReplayJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_job.PreparedMailboxReplayJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_job.MailboxReplayJobRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_job.MailboxReplayJobIntake) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_job.MailboxReplayJobReady) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_job.MailboxReplayJobResult) == type);
    try std.testing.expect(@TypeOf(client.dm.mailbox.replay_job.MailboxReplayJobClient) == type);
    try std.testing.expect(@TypeOf(client.local.operator.LocalOperatorClientError) == type);
    try std.testing.expect(@TypeOf(client.local.operator.LocalOperatorClientConfig) == type);
    try std.testing.expect(@TypeOf(client.local.operator.LocalKeypair) == type);
    try std.testing.expect(@TypeOf(client.local.operator.LocalEventDraft) == type);
    try std.testing.expect(@TypeOf(client.local.operator.LocalEventInspection) == type);
    try std.testing.expect(@TypeOf(client.local.operator.LocalOperatorClient) == type);
    try std.testing.expect(@TypeOf(client.proof.nip03.Nip03VerifyClientError) == type);
    try std.testing.expect(@TypeOf(client.proof.nip03.Nip03VerifyClientConfig) == type);
    try std.testing.expect(@TypeOf(client.proof.nip03.Nip03VerifyClientStorage) == type);
    try std.testing.expect(@TypeOf(client.proof.nip03.Nip03VerifyJob) == type);
    try std.testing.expect(@TypeOf(client.proof.nip03.Nip03VerifyCachedResult) == type);
    try std.testing.expect(@TypeOf(client.proof.nip03.Nip03VerifyJobResult) == type);
    try std.testing.expect(@TypeOf(client.proof.nip03.Nip03StoredVerificationPlanning) == type);
    try std.testing.expect(@TypeOf(client.proof.nip03.Nip03VerifyClient) == type);
    try std.testing.expect(@TypeOf(client.identity.nip05.Nip05VerifyClientError) == type);
    try std.testing.expect(@TypeOf(client.identity.nip05.Nip05VerifyClientConfig) == type);
    try std.testing.expect(@TypeOf(client.identity.nip05.Nip05VerifyClientStorage) == type);
    try std.testing.expect(@TypeOf(client.identity.nip05.Nip05LookupJob) == type);
    try std.testing.expect(@TypeOf(client.identity.nip05.Nip05VerifyJob) == type);
    try std.testing.expect(@TypeOf(client.identity.nip05.Nip05LookupJobResult) == type);
    try std.testing.expect(@TypeOf(client.identity.nip05.Nip05VerifyJobResult) == type);
    try std.testing.expect(@TypeOf(client.identity.nip05.Nip05RememberedResolutionPlanning) == type);
    try std.testing.expect(@TypeOf(client.identity.nip05.Nip05VerifyClient) == type);
    try std.testing.expect(@TypeOf(client.identity.nip39.Nip39VerifyClientError) == type);
    try std.testing.expect(@TypeOf(client.identity.nip39.Nip39VerifyClientConfig) == type);
    try std.testing.expect(@TypeOf(client.identity.nip39.Nip39VerifyClientStorage) == type);
    try std.testing.expect(@TypeOf(client.identity.nip39.Nip39VerifyJob) == type);
    try std.testing.expect(@TypeOf(client.identity.nip39.Nip39VerifySummary) == type);
    try std.testing.expect(@TypeOf(client.identity.nip39.Nip39VerifyJobResult) == type);
    try std.testing.expect(@TypeOf(client.identity.nip39.Nip39StoredProfilePlanning) == type);
    try std.testing.expect(@TypeOf(client.identity.nip39.Nip39VerifyClient) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_job.PublishJobClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_job.PublishJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_job.PublishJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_job.PublishJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_job.PreparedPublishJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_job.PublishJobRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_job.PublishJobReady) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_job.PublishJobResult) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_job.PublishJobClient) == type);
    try std.testing.expect(@TypeOf(client.relay.publish.PublishClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.publish.PublishClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.publish.PublishClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.publish.PreparedPublishEvent) == type);
    try std.testing.expect(@TypeOf(client.relay.publish.PublishTarget) == type);
    try std.testing.expect(@TypeOf(client.relay.publish.TargetedPublishEvent) == type);
    try std.testing.expect(@TypeOf(client.relay.publish.PublishClient) == type);
    try std.testing.expect(@TypeOf(client.signer.capability.SignerBackendKind) == type);
    try std.testing.expect(@TypeOf(client.signer.capability.SignerOperation) == type);
    try std.testing.expect(@TypeOf(client.signer.capability.SignerOperationMode) == type);
    try std.testing.expect(@TypeOf(client.signer.capability.SignerOperationModes) == type);
    try std.testing.expect(@TypeOf(client.signer.capability.SignerCapabilityProfile) == type);
    try std.testing.expect(@TypeOf(client.signer.capability.SignerPubkeyTextRequest) == type);
    try std.testing.expect(@TypeOf(client.signer.capability.SignerOperationRequest) == type);
    try std.testing.expect(@TypeOf(client.signer.capability.SignerTextResponse) == type);
    try std.testing.expect(@TypeOf(client.signer.capability.SignerOperationResult) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_turn.PublishTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_turn.PublishTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_turn.PublishTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_turn.PublishTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_turn.PublishTurnResult) == type);
    try std.testing.expect(@TypeOf(client.relay.publish_turn.PublishTurnClient) == type);
    try std.testing.expect(@TypeOf(client.relay.auth.RelayAuthClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.auth.RelayAuthClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.auth.RelayAuthClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.auth.RelayAuthTarget) == type);
    try std.testing.expect(@TypeOf(client.relay.auth.RelayAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.auth.PreparedRelayAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.relay.auth.RelayAuthClient) == type);
    try std.testing.expect(@TypeOf(client.relay.directory.RelayDirectoryJobClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.directory.RelayDirectoryJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.directory.RelayDirectoryJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.directory.RelayDirectoryRefreshJob) == type);
    try std.testing.expect(@TypeOf(client.relay.directory.RelayDirectoryRefreshJobResult) == type);
    try std.testing.expect(@TypeOf(client.relay.directory.RelayDirectoryJobClient) == type);
    try std.testing.expect(@TypeOf(client.relay.exchange.RelayExchangeClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.exchange.RelayExchangeClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.exchange.RelayExchangeClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.exchange.PublishExchangeRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.exchange.PublishExchangeOutcome) == type);
    try std.testing.expect(@TypeOf(client.relay.exchange.CountExchangeRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.exchange.CountExchangeOutcome) == type);
    try std.testing.expect(@TypeOf(client.relay.exchange.SubscriptionExchangeRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.exchange.SubscriptionExchangeOutcome) == type);
    try std.testing.expect(@TypeOf(client.relay.exchange.CloseExchangeRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.exchange.RelayExchangeClient) == type);
    try std.testing.expect(@TypeOf(client.relay.query.RelayQueryClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.query.RelayQueryClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.query.RelayQueryClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.query.RelayQueryTarget) == type);
    try std.testing.expect(@TypeOf(client.relay.query.TargetedSubscriptionRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.query.TargetedCountRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.query.TargetedCloseRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.query.RelayQueryClient) == type);
    try std.testing.expect(@TypeOf(client.relay.session.RelaySessionClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.session.RelaySessionClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.session.RelaySessionClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.session.RelaySessionCloseRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.session.RelaySessionClient) == type);
    try std.testing.expect(@TypeOf(client.relay.workspace.RelayWorkspaceClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.workspace.RelayWorkspaceClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.workspace.RelayWorkspaceClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.workspace.RelayWorkspaceRestoreResult) == type);
    try std.testing.expect(@TypeOf(client.relay.workspace.RelayWorkspaceClient) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_job.ReplayJobClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_job.ReplayJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_job.ReplayJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_job.ReplayJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_job.PreparedReplayJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_job.ReplayJobRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_job.ReplayJobIntake) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_job.ReplayJobReady) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_job.ReplayJobResult) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_job.ReplayJobClient) == type);
    try std.testing.expect(@TypeOf(client.relay.replay.RelayReplayClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.replay.RelayReplayClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.replay.RelayReplayClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.replay.RelayReplayTarget) == type);
    try std.testing.expect(@TypeOf(client.relay.replay.TargetedReplayRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.replay.RelayReplayClient) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_checkpoint_advance.ReplayCheckpointAdvanceClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_checkpoint_advance.ReplayCheckpointAdvanceClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_checkpoint_advance.ReplayCheckpointAdvanceState) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_checkpoint_advance.ReplayCheckpointAdvanceCandidate) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_checkpoint_advance.ReplayCheckpointSaveTarget) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_checkpoint_advance.ReplayCheckpointAdvanceClient) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_exchange.RelayReplayExchangeClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_exchange.RelayReplayExchangeClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_exchange.RelayReplayExchangeClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_exchange.ReplayExchangeRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_exchange.ReplayExchangeOutcome) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_exchange.ReplayCloseRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_exchange.RelayReplayExchangeClient) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_turn.RelayReplayTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_turn.RelayReplayTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_turn.RelayReplayTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_turn.ReplayTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_turn.ReplayTurnIntake) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_turn.ReplayTurnResult) == type);
    try std.testing.expect(@TypeOf(client.relay.replay_turn.RelayReplayTurnClient) == type);
    try std.testing.expect(@TypeOf(client.relay.response.RelayResponseClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.response.RelayResponseClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.response.RelaySubscriptionTranscriptStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.response.RelaySubscriptionEventMessage) == type);
    try std.testing.expect(@TypeOf(client.relay.response.RelaySubscriptionEoseMessage) == type);
    try std.testing.expect(@TypeOf(client.relay.response.RelaySubscriptionClosedMessage) == type);
    try std.testing.expect(@TypeOf(client.relay.response.RelaySubscriptionMessageOutcome) == type);
    try std.testing.expect(@TypeOf(client.relay.response.RelayCountMessage) == type);
    try std.testing.expect(@TypeOf(client.relay.response.RelayPublishOkMessage) == type);
    try std.testing.expect(@TypeOf(client.relay.response.RelayNoticeMessage) == type);
    try std.testing.expect(@TypeOf(client.relay.response.RelayAuthChallengeMessage) == type);
    try std.testing.expect(@TypeOf(client.relay.response.RelayResponseClient) == type);
    try std.testing.expect(@TypeOf(client.signer.connect_job.SignerConnectJobClientError) == type);
    try std.testing.expect(@TypeOf(client.signer.connect_job.SignerConnectJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.signer.connect_job.SignerConnectJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.signer.connect_job.SignerConnectJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.signer.connect_job.PreparedSignerConnectJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.signer.connect_job.SignerConnectJobRequest) == type);
    try std.testing.expect(@TypeOf(client.signer.connect_job.SignerConnectJobReady) == type);
    try std.testing.expect(@TypeOf(client.signer.connect_job.SignerConnectJobResult) == type);
    try std.testing.expect(@TypeOf(client.signer.connect_job.SignerConnectJobClient) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientError) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientConfig) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientRequestStorage) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientStorage) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientResumeStorage) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientResumeState) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientSessionPolicyAction) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientSessionPolicyStep) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientSessionPolicyPlan) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientSessionCadenceRequest) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientSessionCadenceWaitReason) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientSessionCadenceWait) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientSessionCadenceStep) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClientSessionCadencePlan) == type);
    try std.testing.expect(@TypeOf(client.signer.session.SignerClient) == type);
    try std.testing.expect(@TypeOf(client.signer.nip44_encrypt_job.SignerNip44EncryptJobClientError) == type);
    try std.testing.expect(@TypeOf(client.signer.nip44_encrypt_job.SignerNip44EncryptJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.signer.nip44_encrypt_job.SignerNip44EncryptJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.signer.nip44_encrypt_job.SignerNip44EncryptJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.signer.nip44_encrypt_job.PreparedSignerNip44EncryptJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.signer.nip44_encrypt_job.SignerNip44EncryptJobRequest) == type);
    try std.testing.expect(@TypeOf(client.signer.nip44_encrypt_job.SignerNip44EncryptJobReady) == type);
    try std.testing.expect(@TypeOf(client.signer.nip44_encrypt_job.SignerNip44EncryptJobResult) == type);
    try std.testing.expect(@TypeOf(client.signer.nip44_encrypt_job.SignerNip44EncryptJobClient) == type);
    try std.testing.expect(@TypeOf(client.signer.pubkey_job.SignerPubkeyJobClientError) == type);
    try std.testing.expect(@TypeOf(client.signer.pubkey_job.SignerPubkeyJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.signer.pubkey_job.SignerPubkeyJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.signer.pubkey_job.SignerPubkeyJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.signer.pubkey_job.PreparedSignerPubkeyJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.signer.pubkey_job.SignerPubkeyJobRequest) == type);
    try std.testing.expect(@TypeOf(client.signer.pubkey_job.SignerPubkeyJobReady) == type);
    try std.testing.expect(@TypeOf(client.signer.pubkey_job.SignerPubkeyJobResult) == type);
    try std.testing.expect(@TypeOf(client.signer.pubkey_job.SignerPubkeyJobClient) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_job.SubscriptionJobClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_job.SubscriptionJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_job.SubscriptionJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_job.SubscriptionJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_job.PreparedSubscriptionJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_job.SubscriptionJobRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_job.SubscriptionJobIntake) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_job.SubscriptionJobReady) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_job.SubscriptionJobResult) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_job.SubscriptionJobClient) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_turn.SubscriptionTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_turn.SubscriptionTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_turn.SubscriptionTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_turn.SubscriptionTurnState) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_turn.SubscriptionTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_turn.SubscriptionTurnIntake) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_turn.SubscriptionTurnCompletion) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_turn.SubscriptionTurnResult) == type);
    try std.testing.expect(@TypeOf(client.relay.subscription_turn.SubscriptionTurnClient) == type);
}

test "root module exposes store runtime transport and boundary namespaces" {
    try std.testing.expect(@TypeOf(store) == type);
    try std.testing.expect(@TypeOf(store.RelayInfoRecord) == type);
    try std.testing.expect(@TypeOf(store.RelayInfoResultPage) == type);
    try std.testing.expect(@TypeOf(store.RelayInfoStore) == type);
    try std.testing.expect(@TypeOf(store.MemoryRelayInfoStore) == type);
    try std.testing.expect(@TypeOf(store.ClientStore) == type);
    try std.testing.expect(@TypeOf(store.ClientEventRecord) == type);
    try std.testing.expect(@TypeOf(store.ClientCheckpointRecord) == type);
    try std.testing.expect(@TypeOf(store.ClientQuery) == type);
    try std.testing.expect(@TypeOf(store.QueryResultPage(store.ClientEventRecord)) == type);
    try std.testing.expect(@TypeOf(store.EventCursor) == type);
    try std.testing.expect(@TypeOf(store.IndexSelection) == type);
    try std.testing.expect(@TypeOf(store.MemoryClientStore) == type);
    try std.testing.expect(@TypeOf(store.SqliteClientStoreInitError) == type);
    try std.testing.expect(@TypeOf(store.SqliteClientStore) == type);
    try std.testing.expect(@TypeOf(store.EventArchive) == type);
    try std.testing.expect(@TypeOf(store.RelayRegistryArchive) == type);
    try std.testing.expect(@TypeOf(store.RelayCheckpointArchive) == type);
    try std.testing.expect(@TypeOf(store.RelayLocalGroupArchive) == type);
    try std.testing.expect(@TypeOf(runtime) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPlanStorage) == type);
    try std.testing.expectEqual(@as(u8, 8), runtime.subscription_specs_capacity);
    try std.testing.expectEqual(@as(u8, 8), runtime.replay_specs_capacity);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCheckpointAction) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPublishAction) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPublishEntry) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPublishStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPublishPlan) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPublishStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolAuthAction) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolAuthEntry) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolAuthStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolAuthPlan) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolAuthStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCheckpointError) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolMemberError) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolMemberRecord) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolMemberStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolMemberSet) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCheckpointRecord) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCheckpointStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCheckpointSet) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCheckpointStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelaySubscriptionError) == type);
    try std.testing.expect(@TypeOf(runtime.RelaySubscriptionSpec) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolSubscriptionAction) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolSubscriptionEntry) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolSubscriptionStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolSubscriptionPlan) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolSubscriptionStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelayCountError) == type);
    try std.testing.expect(@TypeOf(runtime.RelayCountSpec) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCountAction) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCountEntry) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCountStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCountPlan) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolCountStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelayReplayError) == type);
    try std.testing.expect(@TypeOf(runtime.RelayReplaySpec) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolReplayAction) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolReplayEntry) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolReplayStorage) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolReplayPlan) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolReplayStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPool) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolPlan) == type);
    try std.testing.expect(@TypeOf(runtime.RelayPoolStep) == type);
    try std.testing.expect(@TypeOf(runtime.RelayServerSessionError) == type);
    try std.testing.expect(@TypeOf(runtime.RelayServerSessionState) == type);
    try std.testing.expect(@TypeOf(runtime.RelayServerSessionIntake) == type);
    try std.testing.expect(@TypeOf(runtime.RelayServerSessionCloseOutcome) == type);
    try std.testing.expect(@TypeOf(runtime.RelayServerSession) == type);
    try std.testing.expect(@TypeOf(transport) == type);
    try std.testing.expect(@TypeOf(internal_runtime.RelayIoConnection) == type);
    try std.testing.expect(@TypeOf(internal_runtime.Clock) == type);
    try std.testing.expect(@TypeOf(internal_runtime.TaskDriver) == type);
    try std.testing.expect(@TypeOf(transport.HttpClient) == type);
    try std.testing.expect(@TypeOf(transport.HttpError) == type);
    try std.testing.expect(@TypeOf(transport.HttpRequest) == type);
    try std.testing.expect(!@hasDecl(@This(), "relay"));
    try std.testing.expect(@TypeOf(workflows) == type);
    try std.testing.expect(!@hasDecl(@This(), "policy"));
    try std.testing.expect(!@hasDecl(@This(), "sync"));
    try std.testing.expect(!@hasDecl(@This(), "Config"));
    try std.testing.expect(!@hasDecl(@This(), "testing"));
}

test "root smoke uses noztr stable helper" {
    const noztr = @import("noztr");
    const parsed_method = try noztr.nip46_remote_signing.method_parse("connect");
    try std.testing.expectEqual(.connect, parsed_method);
}

test "root smoke pins hardened noztr nip46 direct-helper typed errors" {
    const noztr = @import("noztr");

    var overlong_token: [noztr.limits.tag_item_bytes_max + 1]u8 = undefined;
    @memset(overlong_token[0..], 'a');
    try std.testing.expectError(
        error.InvalidMethod,
        noztr.nip46_remote_signing.method_parse(overlong_token[0..]),
    );

    overlong_token[0] = 'p';
    overlong_token[1] = ':';
    try std.testing.expectError(
        error.InvalidPermission,
        noztr.nip46_remote_signing.permission_parse(overlong_token[0..]),
    );
}

test "phase3 relay directory fetches nip11 over explicit seams" {
    const sdk_store = @import("store/mod.zig");
    const relay_directory = @import("relay/directory.zig");
    const testing = @import("testing/mod.zig");
    const json =
        \\{"name":"alpha","pubkey":"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef","supported_nips":[11,42]}
    ;
    var fake_http = testing.FakeHttp.init("https://relay.test", json);
    var memory_store = sdk_store.MemoryStore{};
    var directory = relay_directory.RelayDirectory.init(memory_store.asRelayInfoStore());
    var url_buffer: [128]u8 = undefined;
    var response_buffer: [256]u8 = undefined;
    var parse_scratch: [4096]u8 = undefined;

    const record = try directory.refresh(
        fake_http.client(),
        "wss://relay.test",
        &url_buffer,
        &response_buffer,
        &parse_scratch,
    );
    try std.testing.expectEqualStrings("wss://relay.test", record.relayUrl());
    try std.testing.expectEqualStrings("alpha", record.nameSlice());
}

test "phase3 session helpers stay internal and explicit" {
    const testing = @import("testing/mod.zig");
    const relay_pool = @import("relay/pool.zig");
    var pool = relay_pool.Pool.init();
    const relay_index = try pool.addRelay("wss://relay.one");
    const relay_session = pool.getRelay(relay_index) orelse unreachable;
    const fake_relay = testing.FakeRelay{
        .relay_url = "wss://relay.one",
        .challenge = "challenge-1",
    };
    try fake_relay.requireAuth(relay_session);
    try std.testing.expect(!relay_session.canSendRequests());
}

test "phase4 exposes the remote signer workflow surface" {
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerSession) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerPubkeyTextRequest) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerRequestContext) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerTextResponse) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerRelayPoolStorage) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerRelayPoolRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerResumeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerResumeState) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerSessionPolicyAction) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerSessionPolicyStep) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerSessionPolicyPlan) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerSessionCadenceRequest) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerSessionCadenceWaitReason) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerSessionCadenceWait) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerSessionCadenceStep) == type);
    try std.testing.expect(@TypeOf(workflows.signer.remote.RemoteSignerSessionCadencePlan) == type);
}

test "phase4b exposes the legacy dm workflow surface" {
    try std.testing.expect(@TypeOf(workflows.dm.legacy.LegacyDmSession) == type);
    try std.testing.expect(@TypeOf(workflows.dm.legacy.LegacyDmError) == type);
    try std.testing.expect(@TypeOf(workflows.dm.legacy.LegacyDmDirectMessageRequest) == type);
    try std.testing.expect(@TypeOf(workflows.dm.legacy.LegacyDmOutboundStorage) == type);
    try std.testing.expect(@TypeOf(workflows.dm.legacy.PreparedLegacyDmEvent) == type);
    try std.testing.expect(@TypeOf(workflows.dm.legacy.LegacyDmMessageOutcome) == type);
}

test "phase4c exposes the legacy dm publish job floor" {
    try std.testing.expect(@TypeOf(client.dm.legacy.publish_job.LegacyDmPublishJobClientError) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.publish_job.LegacyDmPublishJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.publish_job.LegacyDmPublishJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.publish_job.LegacyDmPublishJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.publish_job.PreparedLegacyDmPublishJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.publish_job.LegacyDmPublishJobRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.publish_job.LegacyDmPublishJobReady) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.publish_job.LegacyDmPublishJobResult) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.publish_job.LegacyDmPublishJobClient) == type);
}

test "phase4d exposes the legacy dm transcript turn floors" {
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_turn.LegacyDmReplayTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_turn.LegacyDmReplayTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_turn.LegacyDmReplayTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_turn.LegacyDmReplayTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_turn.LegacyDmReplayTurnIntake) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_turn.LegacyDmReplayTurnResult) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_turn.LegacyDmReplayTurnClient) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_turn.LegacyDmSubscriptionTurnClientError) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_turn.LegacyDmSubscriptionTurnClientConfig) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_turn.LegacyDmSubscriptionTurnClientStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_turn.LegacyDmSubscriptionTurnRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_turn.LegacyDmSubscriptionTurnIntake) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_turn.LegacyDmSubscriptionTurnResult) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_turn.LegacyDmSubscriptionTurnClient) == type);
}

test "phase4e exposes the legacy dm replay live runtime floors" {
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_job.LegacyDmReplayJobClientError) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_job.LegacyDmReplayJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_job.LegacyDmReplayJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_job.LegacyDmReplayJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_job.PreparedLegacyDmReplayJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_job.LegacyDmReplayJobRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_job.LegacyDmReplayJobIntake) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_job.LegacyDmReplayJobReady) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_job.LegacyDmReplayJobResult) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.replay_job.LegacyDmReplayJobClient) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_job.LegacyDmSubscriptionJobClientError) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_job.LegacyDmSubscriptionJobClientConfig) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_job.LegacyDmSubscriptionJobClientStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_job.LegacyDmSubscriptionJobAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_job.PreparedLegacyDmSubscriptionJobAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_job.LegacyDmSubscriptionJobRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_job.LegacyDmSubscriptionJobIntake) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_job.LegacyDmSubscriptionJobReady) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_job.LegacyDmSubscriptionJobResult) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.subscription_job.LegacyDmSubscriptionJobClient) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimeClientError) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimeClientConfig) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimeClientStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimeResumeStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimeResumeState) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimePlanStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimePlan) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimeStep) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmLongLivedDmPolicyStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmLongLivedDmPolicyStep) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmLongLivedDmPolicyPlan) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmOrchestrationStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmOrchestrationStep) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmOrchestrationPlan) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmRuntimeCadenceRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmRuntimeCadenceStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmRuntimeCadenceWaitReason) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmRuntimeCadenceWait) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmRuntimeCadenceStep) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmRuntimeCadencePlan) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimeAuthEventStorage) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.PreparedLegacyDmSyncRuntimeAuthEvent) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimeReplayRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimeReplayIntake) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimeSubscriptionRequest) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimeSubscriptionIntake) == type);
    try std.testing.expect(@TypeOf(client.dm.legacy.sync_runtime.LegacyDmSyncRuntimeClient) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientError) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientConfig) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientBackgroundRequest) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientCheckpointStorage) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientCheckpointRequest) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientMergeSelection) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientMergeStorage) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientMergeRequest) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientPublishStorage) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientPutUserDraft) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientRemoveUserDraft) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientPublishRequest) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClientStorage) == type);
    try std.testing.expect(@TypeOf(client.groups.fleet.GroupFleetClient) == type);
}

test "phase5 exposes the mailbox workflow surface" {
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxSession) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxOutboundBuffer) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxFileMessageOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxEnvelopeOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxFileDimensions) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxDeliveryStorage) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxDeliveryRole) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxDeliveryPlan) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxDeliveryStep) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxRuntimeAction) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxRuntimeEntry) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxRuntimeStep) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxRelayPoolStorage) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxRelayPoolRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxWorkflowAction) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxWorkflowEntry) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxWorkflowStep) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxWorkflowStorage) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxWorkflowRequest) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxWorkflowPlan) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxRuntimePlan) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxReceiveTurnStorage) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxReceiveTurnRequest) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxReceiveTurnResult) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxSyncTurnStorage) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxSyncTurnRequest) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxSyncTurnResult) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxDirectMessageRequest) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxFileMessageRequest) == type);
    try std.testing.expect(@TypeOf(workflows.dm.mailbox.MailboxOutboundMessage) == type);
}

test "phase6 exposes the identity verifier workflow surface" {
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityVerifier) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityVerificationCacheResult) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityVerificationCacheRecord) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityVerificationCacheError) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityVerificationCache) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.MemoryIdentityVerificationCache) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityProfileStorePutOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityProfileStoreError) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredClaim) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityProfileRecord) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityProfileMatch) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityProfileDiscoveryRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileDiscoveryEntry) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileDiscoveryStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileDiscoveryRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityLatestStoredProfileRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileFreshness) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileFallbackPolicy) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityLatestStoredProfileFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityLatestStoredProfileFreshness) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityPreferredStoredProfileRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityPreferredStoredProfile) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileDiscoveryFreshnessEntry) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileDiscoveryFreshnessStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileDiscoveryFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTarget) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityWatchedTargetStoreError) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityWatchedTargetRecord) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityWatchedTargetResultPage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetDiscoveryGroup) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetDiscoveryStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetDiscoveryRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetDiscoveryFreshnessGroup) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetDiscoveryFreshnessStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetDiscoveryFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityLatestStoredProfileTargetEntry) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityLatestStoredProfileTargetStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityLatestStoredProfileTargetRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityPreferredStoredProfileTargetEntry) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityPreferredStoredProfileTargetStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityPreferredStoredProfileTargetSelectionRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetLatestFreshnessEntry) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetLatestFreshnessStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetLatestFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedIdentityRecord) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedIdentityResultPage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedIdentityPlanningError) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedIdentityLatestFreshnessStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedIdentityLatestFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedIdentityLatestFreshnessPlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedIdentityRefreshCadenceStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedIdentityRefreshCadenceRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedIdentityRefreshCadencePlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedIdentityRefreshBatchStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedIdentityRefreshBatchRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedIdentityRefreshBatchPlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityPreferredStoredProfileTargetRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityPreferredStoredProfileTarget) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshEntry) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshPlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshStep) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRuntimeAction) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRuntimeRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRuntimePlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRuntimeStep) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetPolicyEntry) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetPolicyGroup) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetPolicyStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetPolicyRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetPolicyPlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshCadenceAction) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshCadenceEntry) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshCadenceGroup) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshCadenceStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshCadenceRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshCadencePlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshCadenceStep) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshBatchStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshBatchRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshBatchPlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetRefreshBatchStep) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetTurnPolicyAction) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetTurnPolicyEntry) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetTurnPolicyGroup) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetTurnPolicyStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetTurnPolicyRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetTurnPolicyPlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetTurnPolicyStep) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetPolicyError) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetPolicyStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetPolicyRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetPolicyPlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetRefreshCadenceError) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetRefreshCadenceStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetRefreshCadenceRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetRefreshCadencePlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetRefreshBatchError) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetRefreshBatchStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetRefreshBatchRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetRefreshBatchPlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetOrchestrationError) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetOrchestrationStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetOrchestrationRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetOrchestrationPlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetTurnPolicyError) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetTurnPolicyStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetTurnPolicyRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredWatchedTargetTurnPolicyPlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetLatestFreshnessPlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileTargetLatestFreshnessStep) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileRuntimeAction) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileRuntimeRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileRuntimePlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileRuntimeStep) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileRefreshEntry) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileRefreshStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileRefreshRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileRefreshPlan) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileRefreshStep) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityProfileStore) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.MemoryIdentityProfileStore) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityWatchedTargetStore) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.MemoryIdentityWatchedTargetStore) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityVerificationStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityVerificationRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityProviderDetails) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityClaimVerificationOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityClaimVerification) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityProfileVerificationStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityProfileVerificationRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityProfileVerificationSummary) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedProfileVerification) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityRememberedProfileVerificationError) == type);
    try std.testing.expect(@TypeOf(workflows.identity.verify.IdentityStoredProfileDiscoveryError) == type);
}

test "phase7 exposes the opentimestamps verifier workflow surface" {
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsVerifier) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsProofStoreError) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsProofRecord) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsProofStore) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.MemoryOpenTimestampsProofStore) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsVerificationStorePutOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsVerificationStoreError) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationRecord) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationMatch) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsVerificationDiscoveryRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationDiscoveryEntry) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationDiscoveryStorage) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationDiscoveryRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsLatestStoredVerificationRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationFreshness) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsLatestStoredVerificationFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsLatestStoredVerificationFreshness) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationDiscoveryFreshnessEntry) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationDiscoveryFreshnessStorage) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationDiscoveryFreshnessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTarget) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsLatestStoredVerificationTargetEntry) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsLatestStoredVerificationTargetStorage) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsLatestStoredVerificationTargetRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationFallbackPolicy) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsPreferredStoredVerificationRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsPreferredStoredVerification) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsPreferredStoredVerificationTargetEntry) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsPreferredStoredVerificationTargetStorage) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsPreferredStoredVerificationTargetRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationRuntimeAction) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationRuntimeRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationRuntimePlan) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationRuntimeStep) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationRefreshEntry) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationRefreshStorage) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationRefreshRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationRefreshPlan) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationRefreshStep) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshEntry) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshStorage) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshPlan) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshStep) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshReadinessError) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshReadinessAction) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshReadinessEntry) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshReadinessGroup) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshReadinessStorage) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshReadinessRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshReadinessPlan) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshReadinessStep) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetPolicyEntry) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetPolicyGroup) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetPolicyStorage) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetPolicyRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetPolicyPlan) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshCadenceAction) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshCadenceEntry) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshCadenceGroup) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshCadenceStorage) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshCadenceRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshCadencePlan) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshCadenceStep) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshBatchStorage) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshBatchRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshBatchPlan) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetRefreshBatchStep) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetTurnPolicyAction) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetTurnPolicyEntry) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetTurnPolicyGroup) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetTurnPolicyStorage) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetTurnPolicyRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetTurnPolicyPlan) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationTargetTurnPolicyStep) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsVerificationStore) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.MemoryOpenTimestampsVerificationStore) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsRemoteProofRequest) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsRemoteVerification) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsRememberedRemoteVerification) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsRememberedRemoteVerificationError) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsStoredVerificationDiscoveryError) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsFetchFailure) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsRemoteVerificationOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.proof.nip03.OpenTimestampsRememberedRemoteVerificationOutcome) == type);
}

test "phase8 exposes the nip05 resolver workflow surface" {
    try std.testing.expect(@TypeOf(workflows.identity.nip05.Nip05Resolver) == type);
    try std.testing.expect(@TypeOf(workflows.identity.nip05.Nip05LookupStorage) == type);
    try std.testing.expect(@TypeOf(workflows.identity.nip05.Nip05LookupRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.nip05.Nip05VerificationRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.nip05.Nip05RememberedResolutionStore) == type);
    try std.testing.expect(@TypeOf(workflows.identity.nip05.MemoryNip05RememberedResolutionStore) == type);
    try std.testing.expect(@TypeOf(workflows.identity.nip05.Nip05LatestRememberedResolutionTargetRequest) == type);
    try std.testing.expect(@TypeOf(workflows.identity.nip05.Nip05RememberedResolutionRefreshRequest) == type);
}

test "phase9 exposes the group session workflow surface" {
    try std.testing.expect(@TypeOf(workflows.groups.local.GroupClient) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleet) == type);
    try std.testing.expect(@TypeOf(workflows.groups.local.GroupRelayState) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetRelayStatus) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetRuntimeAction) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetBackgroundAction) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetBackgroundEntry) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetBackgroundRuntimeStep) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetBackgroundRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetBackgroundRuntimeRequest) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetBackgroundRuntimePlan) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetRuntimeEntry) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetRuntimeStep) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetRuntimeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetRuntimePlan) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetEventOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetBatchOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetRelayDivergence) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetConsistencyReport) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetConsistencyStep) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetReconcileOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetTargetReconcileOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetPublishStep) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetMergeSelection) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetMergedCheckpoint) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetMergeApplyOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetCheckpointStorage) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetMergeStorage) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetCheckpointContext) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetMergeContext) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetCheckpointSet) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetCheckpointStorePutOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetCheckpointStoreError) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetCheckpointRecord) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetCheckpointStore) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.MemoryGroupFleetCheckpointStore) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetStorePersistOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetStoreRestoreOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetPublishStorage) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetPublishContext) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetPutUserDraft) == type);
    try std.testing.expect(@TypeOf(workflows.groups.fleet.GroupFleetRemoveUserDraft) == type);
    try std.testing.expect(@TypeOf(workflows.groups.local.GroupCheckpointBuffers) == type);
    try std.testing.expect(@TypeOf(workflows.groups.local.GroupCheckpointContext) == type);
    try std.testing.expect(@TypeOf(workflows.groups.local.GroupCheckpoint) == type);
    try std.testing.expect(@TypeOf(workflows.groups.local.GroupClientStorage) == type);
    try std.testing.expect(@TypeOf(workflows.groups.local.GroupClientConfig) == type);
    try std.testing.expect(@TypeOf(workflows.groups.local.GroupClientView) == type);
    try std.testing.expect(@TypeOf(workflows.groups.local.GroupClientEventOutcome) == type);
    try std.testing.expect(@TypeOf(workflows.groups.local.GroupClientBatchSummary) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupSession) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupSessionStorage) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupSessionConfig) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupSessionView) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupOutboundBuffer) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupPublishContext) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupOutboundEvent) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupMetadataDraft) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupAdminsDraft) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupMembersDraft) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupRolesDraft) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupJoinRequestDraft) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupLeaveRequestDraft) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupPutUserDraft) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupRemoveUserDraft) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupObservedEventKind) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupJoinRequestInfo) == type);
    try std.testing.expect(@TypeOf(workflows.groups.session.GroupLeaveRequestInfo) == type);
}
